// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {git} from '../models';
import {types} from '../models';
import {context} from '../models';

export function AddCommandRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddPermissionRule(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<void>;

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function AddSEWorker(arg1:string):Promise<main.SEWorker>;

export function AssignTaskToSE(arg1:string,arg2:string):Promise<void>;

export function CheckAllEnv():Promise<Record<string, any>>;

export function CheckCommandSafety(arg1:string):Promise<Record<string, any>>;

export function CheckDecisionForOperation(arg1:string):Promise<Record<string, any>>;

export function CheckEnv(arg1:string):Promise<boolean>;

export function CheckEnvDetail(arg1:string):Promise<main.CheckResult>;

export function CheckFilePermission(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckFileUpdated(arg1:string,arg2:number):Promise<boolean>;

export function CheckPortListening(arg1:number):Promise<boolean>;

export function CheckProcessExists(arg1:string):Promise<boolean>;

export function CheckUnfinishedTask():Promise<boolean>;

export function ClearMessages():Promise<void>;

export function ClearWorkDir():Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function EnvMemorySummary():Promise<string>;

export function ExecuteReset(arg1:string):Promise<void>;

export function FixPosition():Promise<void>;

export function ForceQuit():Promise<void>;

export function GetBranches():Promise<Array<git.BranchInfo>>;

export function GetChangeHistory():Promise<Array<main.ChangeRecord>>;

export function GetCommandPolicy():Promise<types.CommandPolicy>;

export function GetCommitDiff(arg1:string):Promise<Record<string, any>>;

export function GetCommitLog(arg1:number):Promise<Array<git.CommitLogEntry>>;

export function GetConfig():Promise<main.Config>;

export function GetCurrentAPIConfigID():Promise<string>;

export function GetDecisionConfig():Promise<types.DecisionConfig>;

export function GetDingTalkConfig():Promise<main.DingTalkConfig>;

export function GetEnvMemory():Promise<types.EnvMemory>;

export function GetFileDiff(arg1:string):Promise<Record<string, any>>;

export function GetGitStatus():Promise<Array<main.GitStatusEntry>>;

export function GetLogs():Promise<Array<string>>;

export function GetMessages():Promise<Array<main.ChatMessage>>;

export function GetPendingQueue():Promise<Array<string>>;

export function GetPermissionConfig():Promise<types.PermissionConfig>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetRemotes():Promise<Array<git.RemoteInfo>>;

export function GetRepoInfo():Promise<Record<string, any>>;

export function GetSEWorkers():Promise<Array<main.SEWorker>>;

export function GetStatus():Promise<main.MonitorStatus>;

export function GetToolPath(arg1:string):Promise<string|boolean>;

export function GetWorkDir():Promise<string>;

export function GitClone(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GitInit():Promise<void>;

export function GitPull(arg1:string,arg2:string):Promise<string>;

export function GitPush(arg1:string,arg2:string):Promise<string>;

export function HandleBeforeClose(arg1:context.Context):Promise<void>;

export function HandleBeforeCloseSmart(arg1:context.Context):Promise<boolean>;

export function HasActiveTask():Promise<boolean>;

export function InstallEnv(arg1:string):Promise<Record<string, any>>;

export function IsAIThinking():Promise<boolean>;

export function IsAPThinking():Promise<boolean>;

export function IsCMonitorRunning():Promise<boolean>;

export function IsCRunning():Promise<boolean>;

export function IsPMThinking():Promise<boolean>;

export function IsSERunning():Promise<boolean>;

export function IsTerminalRunning():Promise<boolean>;

export function LearnTool(arg1:string,arg2:string):Promise<void>;

export function ListFiles():Promise<Array<Record<string, any>>>;

export function LogPMAudit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NewTerminalSession(arg1:string):Promise<string>;

export function OnWindowDidShow(arg1:context.Context):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function OpenPowerShell(arg1:string):Promise<void>;

export function OpenWorkDir():Promise<void>;

export function ParseTestResult(arg1:string):Promise<main.TestResult>;

export function ReadFile(arg1:string):Promise<string>;

export function RecoverTask():Promise<Array<main.ChatMessage>>;

export function RemoveCommandRule(arg1:string):Promise<void>;

export function RemovePermissionRule(arg1:string):Promise<void>;

export function RemoveRemote(arg1:string):Promise<void>;

export function ResetCommandPolicyToDefault():Promise<void>;

export function ResetDecisionToDefault():Promise<void>;

export function ResetPermissionToDefault():Promise<void>;

export function ResetRoleStatus():Promise<void>;

export function RestoreFile(arg1:string):Promise<void>;

export function ReviewSEWork(arg1:string):Promise<main.PMReviewResult>;

export function RunCommand(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function RunCommandAsync(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function RunCommandWithOutput(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveDingTalkConfig(arg1:main.DingTalkConfig):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveVersion(arg1:string):Promise<void>;

export function SendCLI(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetGitCredentials(arg1:string,arg2:string):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetTerminalEncoding(arg1:string):Promise<void>;

export function SetWorkDir(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function StartCMonitor():Promise<void>;

export function StartHTTPServer():Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCMonitor():Promise<void>;

export function StopCurrentTask():Promise<void>;

export function StopHTTPServer():Promise<void>;

export function StopTerminal():Promise<void>;

export function SwitchAPIConfig(arg1:string):Promise<void>;

export function SwitchBranch(arg1:string):Promise<void>;

export function SwitchTerminalSession(arg1:string):Promise<void>;

export function TestAPIConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.APITestResult>;

export function TrackFile(arg1:string):Promise<void>;

export function UnTrackFile(arg1:string):Promise<void>;

export function UpdateDecisionRule(arg1:string,arg2:string):Promise<void>;

export function UpdateFile(arg1:string,arg2:string):Promise<void>;

export function UpdateProjectState(arg1:string,arg2:string):Promise<void>;

export function VerifySEWork(arg1:string):Promise<Array<main.VerificationResult>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteToTerminal(arg1:string):Promise<void>;
