// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckMessage(arg1) {
  return window['go']['main']['App']['AckMessage'](arg1);
}

export function AddCommandRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCommandRule'](arg1, arg2, arg3);
}

export function AddPermissionRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddPermissionRule'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRemote(arg1, arg2) {
  return window['go']['main']['App']['AddRemote'](arg1, arg2);
}

export function AddSEWorker(arg1) {
  return window['go']['main']['App']['AddSEWorker'](arg1);
}

export function AssignTaskToSE(arg1, arg2) {
  return window['go']['main']['App']['AssignTaskToSE'](arg1, arg2);
}

export function CheckAllEnv() {
  return window['go']['main']['App']['CheckAllEnv']();
}

export function CheckCommandSafety(arg1) {
  return window['go']['main']['App']['CheckCommandSafety'](arg1);
}

export function CheckDecisionForOperation(arg1) {
  return window['go']['main']['App']['CheckDecisionForOperation'](arg1);
}

export function CheckEnv(arg1) {
  return window['go']['main']['App']['CheckEnv'](arg1);
}

export function CheckEnvDetail(arg1) {
  return window['go']['main']['App']['CheckEnvDetail'](arg1);
}

export function CheckFilePermission(arg1, arg2) {
  return window['go']['main']['App']['CheckFilePermission'](arg1, arg2);
}

export function CheckFileUpdated(arg1, arg2) {
  return window['go']['main']['App']['CheckFileUpdated'](arg1, arg2);
}

export function CheckPortListening(arg1) {
  return window['go']['main']['App']['CheckPortListening'](arg1);
}

export function CheckProcessExists(arg1) {
  return window['go']['main']['App']['CheckProcessExists'](arg1);
}

export function CheckUnfinishedTask() {
  return window['go']['main']['App']['CheckUnfinishedTask']();
}

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function ClearWorkDir() {
  return window['go']['main']['App']['ClearWorkDir']();
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function EmitTaskClarify(arg1) {
  return window['go']['main']['App']['EmitTaskClarify'](arg1);
}

export function EnvMemorySummary() {
  return window['go']['main']['App']['EnvMemorySummary']();
}

export function ExecuteReset(arg1) {
  return window['go']['main']['App']['ExecuteReset'](arg1);
}

export function FixPosition() {
  return window['go']['main']['App']['FixPosition']();
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetChangeHistory() {
  return window['go']['main']['App']['GetChangeHistory']();
}

export function GetCommandPolicy() {
  return window['go']['main']['App']['GetCommandPolicy']();
}

export function GetCommitDiff(arg1) {
  return window['go']['main']['App']['GetCommitDiff'](arg1);
}

export function GetCommitLog(arg1) {
  return window['go']['main']['App']['GetCommitLog'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConsistencyReport() {
  return window['go']['main']['App']['GetConsistencyReport']();
}

export function GetCurrentAPIConfigID() {
  return window['go']['main']['App']['GetCurrentAPIConfigID']();
}

export function GetDecisionConfig() {
  return window['go']['main']['App']['GetDecisionConfig']();
}

export function GetDingTalkConfig() {
  return window['go']['main']['App']['GetDingTalkConfig']();
}

export function GetEnvMemory() {
  return window['go']['main']['App']['GetEnvMemory']();
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetGlobalTasks() {
  return window['go']['main']['App']['GetGlobalTasks']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMCPManager() {
  return window['go']['main']['App']['GetMCPManager']();
}

export function GetMessageBusLost() {
  return window['go']['main']['App']['GetMessageBusLost']();
}

export function GetMessageBusPending() {
  return window['go']['main']['App']['GetMessageBusPending']();
}

export function GetMessageBusStats() {
  return window['go']['main']['App']['GetMessageBusStats']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetPendingQueue() {
  return window['go']['main']['App']['GetPendingQueue']();
}

export function GetPermissionConfig() {
  return window['go']['main']['App']['GetPermissionConfig']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetRemotes() {
  return window['go']['main']['App']['GetRemotes']();
}

export function GetRepoInfo() {
  return window['go']['main']['App']['GetRepoInfo']();
}

export function GetSEWorkers() {
  return window['go']['main']['App']['GetSEWorkers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetToolPath(arg1) {
  return window['go']['main']['App']['GetToolPath'](arg1);
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function GitClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitClone'](arg1, arg2, arg3);
}

export function GitInit() {
  return window['go']['main']['App']['GitInit']();
}

export function GitPull(arg1, arg2) {
  return window['go']['main']['App']['GitPull'](arg1, arg2);
}

export function GitPush(arg1, arg2) {
  return window['go']['main']['App']['GitPush'](arg1, arg2);
}

export function HandleBeforeClose(arg1) {
  return window['go']['main']['App']['HandleBeforeClose'](arg1);
}

export function HandleBeforeCloseSmart(arg1) {
  return window['go']['main']['App']['HandleBeforeCloseSmart'](arg1);
}

export function HasActiveTask() {
  return window['go']['main']['App']['HasActiveTask']();
}

export function InstallEnv(arg1) {
  return window['go']['main']['App']['InstallEnv'](arg1);
}

export function IsAIThinking() {
  return window['go']['main']['App']['IsAIThinking']();
}

export function IsAPThinking() {
  return window['go']['main']['App']['IsAPThinking']();
}

export function IsCMonitorRunning() {
  return window['go']['main']['App']['IsCMonitorRunning']();
}

export function IsCRunning() {
  return window['go']['main']['App']['IsCRunning']();
}

export function IsPMThinking() {
  return window['go']['main']['App']['IsPMThinking']();
}

export function IsSERunning() {
  return window['go']['main']['App']['IsSERunning']();
}

export function IsTerminalRunning() {
  return window['go']['main']['App']['IsTerminalRunning']();
}

export function LearnTool(arg1, arg2) {
  return window['go']['main']['App']['LearnTool'](arg1, arg2);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function LogPMAudit(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogPMAudit'](arg1, arg2, arg3);
}

export function NewTerminalSession(arg1) {
  return window['go']['main']['App']['NewTerminalSession'](arg1);
}

export function OnWindowDidShow(arg1) {
  return window['go']['main']['App']['OnWindowDidShow'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenPowerShell(arg1) {
  return window['go']['main']['App']['OpenPowerShell'](arg1);
}

export function OpenWorkDir() {
  return window['go']['main']['App']['OpenWorkDir']();
}

export function ParseTestResult(arg1) {
  return window['go']['main']['App']['ParseTestResult'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RecordReceive(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecordReceive'](arg1, arg2, arg3, arg4);
}

export function RecoverTask() {
  return window['go']['main']['App']['RecoverTask']();
}

export function RemoveCommandRule(arg1) {
  return window['go']['main']['App']['RemoveCommandRule'](arg1);
}

export function RemovePermissionRule(arg1) {
  return window['go']['main']['App']['RemovePermissionRule'](arg1);
}

export function RemoveRemote(arg1) {
  return window['go']['main']['App']['RemoveRemote'](arg1);
}

export function ResetCommandPolicyToDefault() {
  return window['go']['main']['App']['ResetCommandPolicyToDefault']();
}

export function ResetDecisionToDefault() {
  return window['go']['main']['App']['ResetDecisionToDefault']();
}

export function ResetPermissionToDefault() {
  return window['go']['main']['App']['ResetPermissionToDefault']();
}

export function ResetRoleStatus() {
  return window['go']['main']['App']['ResetRoleStatus']();
}

export function RestoreFile(arg1) {
  return window['go']['main']['App']['RestoreFile'](arg1);
}

export function ReviewSEWork(arg1) {
  return window['go']['main']['App']['ReviewSEWork'](arg1);
}

export function RunCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2, arg3);
}

export function RunCommandAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandAsync'](arg1, arg2, arg3);
}

export function RunCommandWithOutput(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandWithOutput'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDingTalkConfig(arg1) {
  return window['go']['main']['App']['SaveDingTalkConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveVersion(arg1) {
  return window['go']['main']['App']['SaveVersion'](arg1);
}

export function SendCLI(arg1) {
  return window['go']['main']['App']['SendCLI'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetGitCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetGitCredentials'](arg1, arg2);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetTerminalEncoding(arg1) {
  return window['go']['main']['App']['SetTerminalEncoding'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartCMonitor() {
  return window['go']['main']['App']['StartCMonitor']();
}

export function StartHTTPServer() {
  return window['go']['main']['App']['StartHTTPServer']();
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopCMonitor() {
  return window['go']['main']['App']['StopCMonitor']();
}

export function StopCurrentTask() {
  return window['go']['main']['App']['StopCurrentTask']();
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function SwitchAPIConfig(arg1) {
  return window['go']['main']['App']['SwitchAPIConfig'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function SwitchTerminalSession(arg1) {
  return window['go']['main']['App']['SwitchTerminalSession'](arg1);
}

export function TerminalTabComplete(arg1) {
  return window['go']['main']['App']['TerminalTabComplete'](arg1);
}

export function TestAPIConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestAPIConfig'](arg1, arg2, arg3, arg4);
}

export function TrackFile(arg1) {
  return window['go']['main']['App']['TrackFile'](arg1);
}

export function UnTrackFile(arg1) {
  return window['go']['main']['App']['UnTrackFile'](arg1);
}

export function UpdateDecisionRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateDecisionRule'](arg1, arg2);
}

export function UpdateFile(arg1, arg2) {
  return window['go']['main']['App']['UpdateFile'](arg1, arg2);
}

export function UpdateProjectState(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectState'](arg1, arg2);
}

export function UserSendMessage(arg1) {
  return window['go']['main']['App']['UserSendMessage'](arg1);
}

export function VerifySEWork(arg1) {
  return window['go']['main']['App']['VerifySEWork'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteToTerminal(arg1) {
  return window['go']['main']['App']['WriteToTerminal'](arg1);
}
